name: Feature request
description: An idea for rPlayFling
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why / how you would use it
